import React, { FC } from "react";
import { CopyBlock, dracula } from "react-code-blocks";
import TableBase from "../table/Base";

const BonusCasesPage: FC = () => {
  return (
    <div className="flex flex-col gap-6">
      <div>
        <h3 className="font-semibold text-white text-[18px] uppercase">
          Bonus Cases technical details
        </h3>

        <div className="flex flex-col gap-3 mt-4">
          <p className="font-normal text-[12px] text-[#D1D1D1] leading-5">
            The result for each case opening is generated by the following
            logic.
          </p>
          <p className="font-normal text-[12px] text-[#D1D1D1] leading-5">
            <span className="text-[#E9AE15]"> 1 ― </span> The server seed is a
            cryptographically secure pseudo-randomly generated string
          </p>
          <p className="font-normal text-[12px] text-[#D1D1D1] leading-5">
            <span className="text-[#E9AE15]"> 2 ― </span> The nonce is a number
            that is incremented every time the server seed is used
          </p>
          <p className="font-normal text-[12px] text-[#D1D1D1] leading-5">
            <span className="text-[#E9AE15]"> 3 ― </span> The pre-result is
            calculated based on server seed, client seed, nonce and case number.
          </p>
          <p className="font-normal text-[12px] text-[#D1D1D1] leading-5">
            <span className="text-[#E9AE15]"> 4 ― </span> The client seed is a
            user-defined (or random by default) string. You can change this to
            be whatever you want from the info tab.
          </p>
          <p className="font-normal text-[12px] text-[#D1D1D1] leading-5">
            <span className="text-[#E9AE15]"> 5 ― </span> Then we pick a result
            between 1 and qty, where the qty is the total number of tickets
            (determined by the chosen case).
          </p>
          <p className="font-normal text-[12px] text-[#D1D1D1] leading-5">
            <span className="text-[#E9AE15]"> 6 ― </span> TEvery item in the
            case has its own number range, which is used to pick the winning
            item based on the result.
          </p>
        </div>

        <p className="font-normal text-[12px] text-[#D1D1D1] leading-5 mt-10">
          You can replicate any past case-opening result yourself using this PHP
          code. Please note that you should use the unhashed (not hashed) server
          seed with the script. You can get the unhashed server seed by going to
          the Info tab and clicking `Regenerate` under Server Seed. When a new
          Server Seed is generated, the nonce resets back to 1. Our provably
          fair code was updated on April 18th, 2024. Cases opened before April
          18th, 2024 until December 5th, 2023, should use this PHP code. Cases
          opened from December 5th, 2023 until December 9th, 2019, should use
          this PHP code. Cases opened before December 9th, 2019, should use this
          PHP code.
        </p>

        {/* <div className="mt-5">
          <TableBase />
        </div> */}
      </div>
    </div>
  );
};

export default BonusCasesPage;
